                             OBJECT (10/19/95)
> unwield temples       You rub your temples.
> point   scratch       You scratch your head.
> nod     clutch        You clutch at your head.
> poke    cock          You cock your head to the side.
> pet     cover         You cover your mouth with your hands.
> tick    pucker        You pucker up your lips.
> unlatch purse         You purse your lips.
> lic     bite          You bite your lower lip.
> scowl   stick         You stick your tongue out.
> growl   grit          You grit your teeth.
> sniff   wrinkle       You wrinkle your nose up.
> wave    wiggle        You wiggle your ears.
> list    clear         You clear your throat.
> slap    chest         You touch your chest.
> tap     puff          You puff your cheeks out!
> open    open          You open your eyes.
> close   close         You close your eyes.
> sell    gaze          You gaze out into space.
> gaze    bug           You bug your eyes out.
> blink   squint        You squint your eyes.
> wink    bat           You bat your eyelashes.
> frow    pale          You feel your face grow pale.
> glare   emotions      You feel a wave of emotions pass over your face.
> bow     look up       You look up.
> curt    look down     You look down.
> eat     growl         Your stomach growls.
> nib     mumble        You mumble something incoherent.
> kiss    hum           You humm softly to yourself.
> whistle whistle       You whistle innocently.
> punch   sneeze        You sneeze.
> lean    snore         You snore. 
> toast   laugh         You laugh maniacally.
> raise   tears         You feel tears roll down your cheeks.
> hug     sniffle       You sniffle.
> curse   cry           You cry out in agony.
> appr    fume          You fume.
> pinch   squeek        You squeek!
> rub     rub           You rub your hands together.
> ignite  knuckles      You crack your knuckles.
> light   knuckles      You crack your knuckles.
> knoc    fold          You fold your arms.
> thump   fold          You fold your arms.
> drop    sweat         You wipe your brow.
> headsha despair       You throw your hands up in despair.
> wield   symbol        You trace a small symbol over your heart.
> kic     slouch        You slouch a bit.
> spit    fall          You let your body go limp and fall to the ground.
> massa   pose          You strike a pose and flex your biceps.
> caress  fingers       You run your fingers through your hair.
> dri     stagger       You stagger about drunkenly.
> latch   flourish      You bow with a flourish.
> salu    attention     You stand at attention.
> turn    twirl         You twirl around.
> pro     bounce        You bounce up and down. (or around the fountain)
> wear    inventory     You take inventory.
> flip    blanky        You gaze about the area blankly.
> gesture gate/fountain You peer through the gate/You look at your reflection

                            INTERESTING PHRASES

spit      me         You drool all over yourself.
lick      me         You lick your lips.
laugh     me         You laugh at yourself.
kick      me         You kick yourself.
thump     me         You thump yourself on the head.
kiss      <person>   [head, nose, lips, ears, neck, chest, hand]
kiss      <person>   [navel, leg, knee, feet]
lick      <person>   You kiss <person> passionately. (If not submitted.)
lick      <person>   You lick <person> all over their body. (If submitted.)
kick      boots      You stamp the dust from your boots.
pull      beard      You tug at your beard.
pull      breeches   You tug at your breeches.
whisper   <NPC>      A <NPC> looks at you oddly.
poke      sheep      You do something unmentionable to a sheep.
pull      cloak      You pull your cloak more tightly about your body.
turn      cloak      You turn around, your cloak swirling dramatically.
rub       cloak      You rummage around underneath your cloak.
wave      cloak      You ruffle your cloak.
rub       armor      You look over the front of your armor and polish out
                       a few dirty spots.
pet       mold       You stroke the gooey surface of your slime mold.
push      mold       You stick your hand into the mold and wriggle your
                       fingers around within it.
pull      mold       You tug at the mold and it creeps up your arm,
                       engulfing it.
lick      mold       As you lean in towards the mold, it lashes out
                       and grabs at your tongue, tugging on it.
pet       eleraan    You stroke the creature's fur.
hug       eleraan    You wrap your arms around the creature.
lick      eleraan    You get a hairy tongue.
turn      pen        You twirl your pen, deep in thought.
lick      pen        You wet the tip of your pen.
push      pen        You write on the parchment.

                             ALPHABETICAL LIST

act     advance analyze applaud appraise        arm     arrest  ascend  assist
attack  avoid
babble  backstab        balance bark    beam    berserk bite    blend
blink   blush   bow     break   brew    brief   buy     
call    caress  cast    chant   chuckle claw    climb   close   comfort cough
cringe  cry     cuddle  curse   curtsy  
dance   defensive       depart  deposit descend destroy diagnose
dig     dip     disarm  disband disguise        drink   drop    duck
eat     echo    emote   enroll  exp     extinguish
fidget  fill    flip    fly     follow  forget  frenzy  frown   furrow
gasp    gaze    gesture giggle  give    glare   go      grimace grin    groan
growl   grunt   guard   gulp    
handraise       handshake       headshake       health  help    hide
hiss    hit     hold    howl    hug     hula    
ignite  info    initiate        inventory
jig     join    jump
kick    kill    kiss    kneel   knock
latch   laugh   lay     lean    learn   leave   lick    light   load    look
mana    mark    massage moan    moderate        mold    mutter
nibble  nod     nudge   nuzzle
open    
pace    pant    pay     peer    pick    pinch   play    point   poke    pour
power   psi     pull    punch   purr    push    put
read    recall  release remove  retreat roar    rob     roll    rub
salute  scowl   scream  search  selftrain       shrug   sing    sit     skin
slap    smelt   smile   smirk   snarl   snicker sniff   snort   snuggle spit
split   stalk   stand   status  steal   stretch submit  swoon
take    tap     teach   tear    thump   tickle  toast   train   transform
turn
unlock  unwield verbose
wag     wait    wary    wave    wealth  wear    weather whisper wield   wince
wink    withdraw        write
yawn    yell    yowl



RELATION

                                EXPRESSIVE

act     applaud bark    beam    blink   blush   bow     chuckle comfort cough   
cry     curse   curtsy  duck    fidget  frown   furrow  gasp    gaze    
gesture giggle  glare   grimace grin    groan   grown   grunt   gulp    
handraise       handshake       headshake       hiss    howl    hug     hula
jig     jump    kick    kiss    kneel   laugh   lay     lean    lick    moan    
mutter  nibble  nod     pace    pinch   point   poke    roar    roll    rub     
salute  scowl   scream  scream  shrug   sing    slap    smirk   snort   
stretch swoon   thump   tickle  toast   turn    wait    wave    wince   wink    
yawn 


